### PR TITLE
Zjr/remove go files

### PR DESCRIPTION
**Pull request by Zach-Bob**
Remove all go files to make way for the elixir implementation of this repo

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
Since all these commits are just individually deleting single files, let's squash all these down into a single commit.  If you need help doing that, let me know.

**Comment by Zach-Bob** [comment]
Alright, I have just squashed all of the deleted file commits into a single commit and pushed the result. I think everything should be all set now.

**Comment by Zach-Bob** [comment]
Woohoo! First official Mojo PR has been merged!

**Comment by cpjolicoeur** [comment]
> Woohoo! First official Mojo PR has been merged!

**Pull request merged**
