### PR TITLE
Use a CoffeeScript linter for the client

### PR DESCRIPTION
**Pull request by anthonyjruffa**
Implement a linter for the CoffeeScript code in the client to help prevent coding inconsistencies.

### CODE REVIEW

**Comment by anthonyjruffa** [comment]
Yeah, I just realized I forgot to put that in the commit.  My bad.

**Comment by begizi** [comment]
:+1: lgtm

**Comment by anthonyjruffa** [comment]
I actually forgot to add the double quotes rule. Will do that soon.

**Comment by anthonyjruffa** [comment]
I also implemented the double quotes rule, and all other comments have been resolved.

**Comment by begizi** [comment]
Let's rebase this off master and confirm green ci before merging

**Comment by anthonyjruffa** [comment]
all set to go :green_apple: :green_heart: :green_book:

**Comment by cpjolicoeur** [comment]
@anthonyjruffa just rebase this off master first please.

**Comment by anthonyjruffa** [comment]
@cpjolicoeur rebased and build is green.

**Pull request closed without merging**
